[package]
name = "visualization"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-s3 = "0.35"  # 建议使用最新版本
tokio = { version = "1", features = ["full"] } # 如果使用异步运行时
base64 = "0.22.1"
data-encoding = "2.11.0"
hex = "0.4.3"
hex-literal = "1.1.0"
image = "0.25.10"
imageproc = "0.27.0"
pbkdf2 = "0.13.0"
plotters = "0.3.7"
qrcode = "0.14.1"
rand = "0.10.1"
rand_core = "0.10.1"
rdrand = "0.9.0"
sha2 = "0.11.0"
kamadak-exif = "0.6.0"
candle-core = "0.9"
ffmpeg-next = "8"
ring = "0.17.14"
aes-gcm = { version = "0.11.0", features = ["getrandom", "arrayvec"] }
arrayvec = { version = "0.7.8", features = ["std"] }
